spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bao_shop?currentSchema=payment
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payment
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    schemas: payment
    default-schema: payment
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8085