spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bao_shop?currentSchema=orders
    username: ${DB_USERNAME:orders_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    schemas: orders
    default-schema: orders
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8084