spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bao_shop?currentSchema=auth
    username: ${DB_USERNAME:auth_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081