spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bao_shop}?currentSchema=${DB_SCHEMA:orders}
    username: ${DB_USERNAME:orders_user}
    password: ${DB_PASSWORD:gbao4132}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:orders}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    schemas: ${DB_SCHEMA:orders}
    default-schema: ${DB_SCHEMA:orders}
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8084}