spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bao_shop?currentSchema=catalog
    username: catalog_user
    password: gbao4132
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: catalog
  flyway:
    enabled: true
    schemas: catalog
    default-schema: catalog
    locations: classpath:db/migration