spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bao_shop?currentSchema=inventory
    username: ${DB_USERNAME:inventory_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: inventory
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    schemas: inventory
    default-schema: inventory
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8083