spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bao_shop?currentSchema=inventory
    username: inventory_user
    password: gbao4132
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: inventory
  flyway:
    enabled: true
    schemas: inventory
    default-schema: inventory
    locations: classpath:db/migration